name: Build Next.js image
on:
  push:
    paths:
      - 'deploy/nextjs/**'
      - '!deploy/nextjs/.next/**'
      - '!deploy/data/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./deploy/nextjs
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/your-nextjs:latest


